# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "chipset_resources"
edition = "2021"
rust-version.workspace = true

[dependencies]
vm_resource.workspace = true

inspect.workspace = true
mesh.workspace = true

arbitrary = { workspace = true, optional = true, features = ["derive"] }

[lints]
workspace = true
