# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "dma_guest_memory_wrapper"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dev-dependencies]
anyhow.workspace = true
chipset_device.workspace = true
guestmem.workspace = true
inspect.workspace = true
parking_lot.workspace = true
pci_core.workspace = true
sparse_mmap.workspace = true
user_driver.workspace = true

[lints]
workspace = true
