# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "disk_storvsc"
edition.workspace = true
rust-version.workspace = true

[features]
test = []

[dependencies]
disk_backend.workspace = true
storvsc_driver.workspace = true

igvm_defs.workspace = true
scsi_buffers.workspace = true
scsi_defs.workspace = true
vmbus_user_channel.workspace = true

storvsp_protocol.workspace = true
inspect.workspace = true
futures.workspace = true
tracing.workspace = true
zerocopy.workspace = true

[dev-dependencies]

[lints]
workspace = true
