# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "fixed_pool_alloc"
edition = "2021"

[features]
vfio = ["user_driver/vfio"]
nvme_keepalive = []

[dependencies]
hcl.workspace = true

user_driver.workspace = true
vm_topology.workspace = true
hvdef.workspace = true
sparse_mmap.workspace = true
# nix = { workspace = true, features = ["mman"] }
libc.workspace = true

inspect.workspace = true

parking_lot.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true

[lints]
workspace = true
