# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "tpm_lib"
rust-version.workspace = true
edition.workspace = true

[features]
default = []
tpm = []

[dependencies]
tpm_protocol.workspace = true
cvm_tracing.workspace = true
inspect.workspace = true
thiserror.workspace = true
tracelimit.workspace = true
tracing.workspace = true
zerocopy.workspace = true
getrandom.workspace = true

[dev-dependencies]
ms-tpm-20-ref = { workspace = true, features = ["vendored"] }

[lints]
workspace = true
