# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "vtpm_util"
edition.workspace = true
rust-version.workspace = true

[features]
experimental = ["dep:ctrlc"]

[[bin]]
name = "vtpm_util_experimental"
path = "src/bin/vtpm_util_experimental.rs"
required-features = ["experimental"]

[dependencies]
base64.workspace = true
clap = { workspace = true, features = ["derive"] }
ctrlc = { workspace = true, optional = true }
getrandom.workspace = true
hex.workspace = true
ms-tpm-20-ref = { workspace = true, features = ["vendored"] }
openssl = { workspace = true, features = ["vendored"] }
parking_lot.workspace = true
sha2.workspace = true
tpm_lib.workspace = true
tpm_protocol.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
zerocopy.workspace = true

[dev-dependencies]
tempfile.workspace = true
test_with_tracing.workspace = true

[lints]
workspace = true
