# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "vtpm_util"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
clap = { workspace = true, features = ["derive"] }
crypto = { workspace = true, features = ["export_private", "native", "vendored"] }
der = { workspace = true, features = ["alloc"] }
getrandom.workspace = true
hex.workspace = true
ms-tpm-20-ref = { workspace = true, features = ["openssl", "vendored"] }
parking_lot.workspace = true
pkcs1.workspace = true
tpm_lib.workspace = true
tpm_protocol.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
zerocopy.workspace = true

[dev-dependencies]
tempfile.workspace = true
test_with_tracing.workspace = true

[lints]
workspace = true
