// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Sivm policy body and validation methods. Accessor
//! `MeasuredPolicy::sivm` is generated by `define_product_policy!`
//! in `lib.rs`.

extern crate alloc;

use alloc::vec::Vec;

/// Sivm policy body.
#[derive(mesh_protobuf::Protobuf, Debug, Clone, PartialEq, Default)]
#[cfg_attr(feature = "manifest", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(
    feature = "manifest",
    serde(rename_all = "snake_case", deny_unknown_fields)
)]
#[cfg_attr(feature = "inspect", derive(inspect::Inspect))]
#[mesh(package = "openhcl.product_policy")]
pub struct SivmPolicy {
    /// Refuse VMGS writes when set.
    #[mesh(1)]
    pub vmgs_read_only: bool,

    /// Refuse to boot unless secure boot is enabled.
    #[mesh(2)]
    pub require_secure_boot: bool,

    /// Refuse to boot unless PK/KEK/db/dbx variables are present.
    #[mesh(3)]
    pub require_secure_boot_vars: bool,

    /// Refuse to boot unless `BootConfigurationDataHash` is set.
    #[mesh(4)]
    pub require_bcd_integrity: bool,

    /// Custom UEFI JSON bytes. Base64 in manifest JSON; mandatory.
    #[mesh(5)]
    #[cfg_attr(feature = "manifest", serde(with = "custom_uefi_json_serde"))]
    #[cfg_attr(feature = "inspect", inspect(with = "Vec::<u8>::len"))]
    pub custom_uefi_json: Vec<u8>,
}

#[cfg(feature = "manifest")]
mod custom_uefi_json_serde {
    extern crate alloc;

    use alloc::format;
    use alloc::string::String;
    use alloc::vec::Vec;
    use base64::Engine as _;
    use serde::Deserialize as _;

    pub fn serialize<S>(bytes: &[u8], s: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        let encoded = base64::engine::general_purpose::STANDARD.encode(bytes);
        s.serialize_str(&encoded)
    }

    pub fn deserialize<'de, D>(d: D) -> Result<Vec<u8>, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = String::deserialize(d)?;
        if s.is_empty() {
            return Ok(Vec::new());
        }
        base64::engine::general_purpose::STANDARD
            .decode(s.as_bytes())
            .map_err(|e| serde::de::Error::custom(format!("failed to base64-decode bytes: {e}")))
    }
}

#[cfg(feature = "std")]
impl SivmPolicy {
    /// Fail if the policy requires secure boot and `on` is false.
    pub fn validate_secure_boot_enabled(&self, on: bool) -> anyhow::Result<()> {
        if self.require_secure_boot && !on {
            anyhow::bail!("Sivm policy requires secure boot to be enabled");
        }
        Ok(())
    }

    /// Parse , enforce Replace mode, and validate
    /// secure boot variables and BCD integrity per policy flags.
    pub fn validate_secure_boot_policy_enforcement(&self) -> anyhow::Result<()> {
        use firmware_uefi_custom_vars::delta::SignaturesDelta;

        let delta = hyperv_uefi_custom_vars_json::load_delta_from_json(&self.custom_uefi_json)
            .map_err(|e| anyhow::anyhow!("failed to parse custom UEFI JSON: {e}"))?;

        let sigs = match delta.signatures {
            SignaturesDelta::Replace(r) => r,
            SignaturesDelta::Append(_) => {
                anyhow::bail!("Sivm policy requires Replace mode for secure boot signatures");
            }
        };

        if self.require_secure_boot_vars {
            use firmware_uefi_custom_vars::delta::SignatureDelta;
            use firmware_uefi_custom_vars::delta::SignatureDeltaVec;

            // All vars must carry explicit signatures —  relies on
            // a base template, which is not self-contained.
            if matches!(sigs.pk, SignatureDelta::Default) {
                anyhow::bail!("Sivm policy: PK uses Default (not self-contained)");
            }
            if matches!(sigs.kek, SignatureDeltaVec::Default) {
                anyhow::bail!("Sivm policy: KEK uses Default (not self-contained)");
            }
            if matches!(sigs.db, SignatureDeltaVec::Default) {
                anyhow::bail!("Sivm policy: db uses Default (not self-contained)");
            }
            if matches!(sigs.dbx, SignatureDeltaVec::Default) {
                anyhow::bail!("Sivm policy: dbx uses Default (not self-contained)");
            }
        }

        if self.require_bcd_integrity {
            let has_bcd_hash = delta
                .custom_vars
                .iter()
                .any(|(name, _)| name == "BootConfigurationDataHash");
            if !has_bcd_hash {
                anyhow::bail!(
                    "Sivm policy: require_bcd_integrity is set but BootConfigurationDataHash variable is missing from custom UEFI JSON"
                );
            }
        }

        Ok(())
    }

    /// Return the custom UEFI JSON bytes after policy validation.
    pub fn get_validated_uefi_json(&self) -> anyhow::Result<&[u8]> {
        if self.custom_uefi_json.is_empty() {
            anyhow::bail!("Sivm policy requires custom UEFI JSON");
        }
        self.validate_secure_boot_policy_enforcement()?;
        Ok(&self.custom_uefi_json)
    }
}

#[cfg(all(test, feature = "std"))]
mod tests {
    use super::*;
    use alloc::string::ToString;

    #[test]
    fn flag_off_passes_either_way() {
        let p = SivmPolicy::default();
        assert!(p.validate_secure_boot_enabled(false).is_ok());
        assert!(p.validate_secure_boot_enabled(true).is_ok());
    }

    #[test]
    fn flag_on_passes_when_secure_boot_is_enabled() {
        let p = SivmPolicy {
            require_secure_boot: true,
            ..Default::default()
        };
        assert!(p.validate_secure_boot_enabled(true).is_ok());
    }

    #[test]
    fn flag_on_fails_when_secure_boot_is_disabled() {
        let p = SivmPolicy {
            require_secure_boot: true,
            ..Default::default()
        };
        let err = p.validate_secure_boot_enabled(false).unwrap_err();
        assert!(err.to_string().contains("secure boot"));
    }
}
