// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Sivm policy body and validation methods. Accessor
//! `MeasuredPolicy::sivm` is generated by `define_product_policy!`
//! in `lib.rs`.

extern crate alloc;

use alloc::vec::Vec;

use crate::uefi_security_policy::UefiSecurityPolicy;

/// Sivm policy body.
#[derive(mesh_protobuf::Protobuf, Debug, Clone, PartialEq, Default)]
#[cfg_attr(feature = "manifest", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(
    feature = "manifest",
    serde(rename_all = "snake_case", deny_unknown_fields)
)]
#[cfg_attr(feature = "inspect", derive(inspect::Inspect))]
#[mesh(package = "openhcl.product_policy")]
pub struct SivmPolicy {
    /// Require an ephemeral VMGS (the attached VMGS must never be read).
    #[mesh(1)]
    pub enforce_ephemeral_vmgs: bool,

    /// Refuse to boot unless secure boot is enabled.
    #[mesh(2)]
    pub require_secure_boot: bool,

    /// Refuse to boot unless PK/KEK/db/dbx variables are present.
    #[mesh(3)]
    pub require_secure_boot_vars: bool,

    /// Refuse to boot unless `BootConfigurationDataHash` is set.
    #[mesh(4)]
    pub require_bcd_integrity: bool,

    /// Custom UEFI JSON bytes. Base64 in manifest JSON; mandatory.
    #[mesh(5)]
    #[cfg_attr(
        feature = "manifest",
        serde(with = "super::product_policy_helpers::custom_uefi_json_serde")
    )]
    #[cfg_attr(feature = "inspect", inspect(with = "Vec::<u8>::len"))]
    pub custom_uefi_json: Vec<u8>,
}

impl crate::uefi_security_policy::UefiSecurityPolicyParams for SivmPolicy {
    fn require_secure_boot(&self) -> bool {
        self.require_secure_boot
    }
}

impl UefiSecurityPolicy for SivmPolicy {}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::string::ToString;

    #[test]
    fn flag_off_passes_either_way() {
        let p = SivmPolicy::default();
        assert!(p.validate_secure_boot_enabled(false).is_ok());
        assert!(p.validate_secure_boot_enabled(true).is_ok());
    }

    #[test]
    fn flag_on_passes_when_secure_boot_is_enabled() {
        let p = SivmPolicy {
            require_secure_boot: true,
            ..Default::default()
        };
        assert!(p.validate_secure_boot_enabled(true).is_ok());
    }

    #[test]
    fn flag_on_fails_when_secure_boot_is_disabled() {
        let p = SivmPolicy {
            require_secure_boot: true,
            ..Default::default()
        };
        let err = p.validate_secure_boot_enabled(false).unwrap_err();
        assert!(err.to_string().contains("secure boot"));
    }
}
