# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "guestmem"
edition.workspace = true
rust-version.workspace = true

[dependencies]
inspect.workspace = true
pal_event.workspace = true
sparse_mmap.workspace = true

thiserror.workspace = true
# TODO: zerocopy: move dependency back to zerocopy.workspace
# after entire workspace upgraded to 0.8.
#zerocopy.workspace = true
zerocopy = "0.8.14"

[lints]
workspace = true
