# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "openvmm_build_info"
edition.workspace = true
rust-version.workspace = true

[build-dependencies]
build_rs_git_info.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }

[lints]
workspace = true
