# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "fast_memcpy"
rust-version.workspace = true
edition.workspace = true

[dependencies]

[lints]
workspace = true
