# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "safe_intrinsics"
edition.workspace = true
rust-version.workspace = true

[dependencies]
cfg-if.workspace = true

[lints]
workspace = true
