# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "gdma_test"
edition.workspace = true
rust-version.workspace = true

[dependencies]
gdma = { workspace = true, features = ["test_helpers"] }
gdma_defs.workspace = true
gdma_resources.workspace = true
pci_resources.workspace = true
vm_resource.workspace = true
pal_async.workspace = true
async-trait.workspace = true
futures.workspace = true
zerocopy.workspace = true

[dev-dependencies]
test_with_tracing.workspace = true

[lints]
workspace = true
