// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! CWCOW (Confidential Windows Container on Windows) policy body
//! and validation methods. Accessor `MeasuredPolicy::cwcow` is
//! generated by `define_product_policy!` in `lib.rs`.

extern crate alloc;

use alloc::vec::Vec;

/// CWCOW policy body.
#[derive(mesh_protobuf::Protobuf, Debug, Clone, PartialEq, Default)]
#[cfg_attr(feature = "manifest", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(
    feature = "manifest",
    serde(rename_all = "snake_case", deny_unknown_fields)
)]
#[cfg_attr(feature = "inspect", derive(inspect::Inspect))]
#[mesh(package = "openhcl.product_policy")]
pub struct CwcowPolicy {
    /// Refuse VMGS writes when set.
    #[mesh(1)]
    pub vmgs_read_only: bool,

    /// Refuse to boot unless secure boot is enabled.
    #[mesh(2)]
    pub require_secure_boot: bool,

    /// Refuse to boot unless PK/KEK/db/dbx variables are present.
    #[mesh(3)]
    pub require_secure_boot_vars: bool,

    /// Refuse to boot unless `BootConfigurationDataHash` is set.
    #[mesh(4)]
    pub require_bcd_integrity: bool,

    /// Refuse to boot unless Secure AVIC is enabled.
    #[mesh(5)]
    pub require_secure_avic: bool,

    /// Custom UEFI JSON bytes. Base64 in manifest JSON; mandatory.
    #[mesh(6)]
    #[cfg_attr(feature = "manifest", serde(with = "custom_uefi_json_serde"))]
    #[cfg_attr(feature = "inspect", inspect(with = "Vec::<u8>::len"))]
    pub custom_uefi_json: Vec<u8>,
}

#[cfg(feature = "manifest")]
mod custom_uefi_json_serde {
    extern crate alloc;

    use alloc::format;
    use alloc::string::String;
    use alloc::vec::Vec;
    use base64::Engine as _;
    use serde::Deserialize as _;

    pub fn serialize<S>(bytes: &[u8], s: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        let encoded = base64::engine::general_purpose::STANDARD.encode(bytes);
        s.serialize_str(&encoded)
    }

    pub fn deserialize<'de, D>(d: D) -> Result<Vec<u8>, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = String::deserialize(d)?;
        if s.is_empty() {
            return Ok(Vec::new());
        }
        base64::engine::general_purpose::STANDARD
            .decode(s.as_bytes())
            .map_err(|e| serde::de::Error::custom(format!("failed to base64-decode bytes: {e}")))
    }
}

#[cfg(feature = "std")]
impl CwcowPolicy {
    /// Fail if the policy requires secure boot and `on` is false.
    pub fn validate_secure_boot_enabled(&self, on: bool) -> anyhow::Result<()> {
        if self.require_secure_boot && !on {
            anyhow::bail!("CWCOW policy requires secure boot to be enabled");
        }
        Ok(())
    }
}

#[cfg(all(test, feature = "std"))]
mod tests {
    use super::*;
    use alloc::string::ToString;

    #[test]
    fn flag_off_passes_either_way() {
        let p = CwcowPolicy::default();
        assert!(p.validate_secure_boot_enabled(false).is_ok());
        assert!(p.validate_secure_boot_enabled(true).is_ok());
    }

    #[test]
    fn flag_on_passes_when_secure_boot_is_enabled() {
        let p = CwcowPolicy {
            require_secure_boot: true,
            ..Default::default()
        };
        assert!(p.validate_secure_boot_enabled(true).is_ok());
    }

    #[test]
    fn flag_on_fails_when_secure_boot_is_disabled() {
        let p = CwcowPolicy {
            require_secure_boot: true,
            ..Default::default()
        };
        let err = p.validate_secure_boot_enabled(false).unwrap_err();
        assert!(err.to_string().contains("secure boot"));
    }
}
