name: Upload Petri Test Results

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run ID to upload'
        required: true
        default: 15218018270

permissions:
  id-token: write
  contents: read
  actions: read  # Needed to download artifacts from other runs

jobs:
  upload-logs:
    runs-on: ubuntu-latest
    env:
      RunId: ${{ github.event.inputs.run_id }}

    steps:
      - name: Authenticate to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.OPENVMM_TEST_RESULT_CLIENT_ID }}
          tenant-id: ${{ secrets.OPENVMM_TENANT_ID }}
          subscription-id: ${{ secrets.OPENVMM_SUBSCRIPTION_ID }}

      - name: Download matching artifacts
        run: |
          mkdir -p results
          gh run -R microsoft/openvmm download $RunId -p "*-vmm-tests-logs" -D results
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Azure Blob Storage
        run: |
          az storage blob upload-batch \
            --destination https://openvmmghtestresults.blob.core.windows.net/results \
            --destination-path "ci/$RunId" \
            --source results \
            --auth-mode login \
            --pattern "*/petri.jsonl"
