trigger:
- main
pr: none
variables:
- name: skipComponentGovernanceDetection
  value: 'true'
jobs:
  - job: mirror
    steps:
    - task: TriggerBuild@4
      inputs:
        definitionIsInCurrentTeamProject: true
        buildDefinition: 'openvmm-mirror-refresh'
        queueBuildForUserThatTriggeredBuild: false
        useSameBranch: false
        branchToUse: 'main'
        buildParameters: 'branchToMirror: main, branchToUpdateSubmodule: main'
        authenticationMethod: 'OAuth Token'
        password: '$(System.AccessToken)'
      displayName: Trigger openvmm-mirror-refresh pipeline